### ISSUE TITLE
Huzuni 1.10.2

### ISSUE THREAD

**Issue by eLRumano** [Huzuni/Huzuni-1.11#13]
I have this crash : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You're mean.

Time: 02/03/17 19:12
Description: Rendering screen

java.lang.NumberFormatException: For input string: "0,7"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at java.lang.Float.valueOf(Unknown Source)
	at net.halalaboos.huzuni.api.gui.components.tree.ValueComponent.updateValue(ValueComponent.java:50)
	at net.halalaboos.huzuni.api.gui.components.tree.ValueComponent.update(ValueComponent.java:39)
	at net.halalaboos.huzuni.api.gui.components.tree.NodeTreeComponent.update(NodeTreeComponent.java:37)
	at net.halalaboos.huzuni.api.gui.components.tree.NodeTree.renderTree(NodeTree.java:37)
	at net.halalaboos.huzuni.gui.BasicTheme$NodeTreeRenderer.render(BasicTheme.java:187)
	at net.halalaboos.huzuni.gui.BasicTheme$NodeTreeRenderer.render(BasicTheme.java:175)
	at net.halalaboos.huzuni.api.gui.Theme.renderComponent(Theme.java:41)
	at net.halalaboos.huzuni.api.gui.Component.render(Component.java:29)
	at net.halalaboos.huzuni.api.gui.components.ScrollableComponent.render(ScrollableComponent.java:27)
	at net.halalaboos.huzuni.api.gui.components.tree.NodeTree.render(NodeTree.java:24)
	at net.halalaboos.huzuni.api.gui.Container.render(Container.java:31)
	at net.halalaboos.huzuni.api.gui.containers.SingleComponentContainer.render(SingleComponentContainer.java:36)
	at net.halalaboos.huzuni.gui.SettingsMenu.renderMenu(SettingsMenu.java:104)
	at net.halalaboos.huzuni.gui.screen.HuzuniSettingsMenu.func_73863_a(HuzuniSettingsMenu.java:32)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at java.lang.Float.valueOf(Unknown Source)
	at net.halalaboos.huzuni.api.gui.components.tree.ValueComponent.updateValue(ValueComponent.java:50)
	at net.halalaboos.huzuni.api.gui.components.tree.ValueComponent.update(ValueComponent.java:39)
	at net.halalaboos.huzuni.api.gui.components.tree.NodeTreeComponent.update(NodeTreeComponent.java:37)
	at net.halalaboos.huzuni.api.gui.components.tree.NodeTree.renderTree(NodeTree.java:37)
	at net.halalaboos.huzuni.gui.BasicTheme$NodeTreeRenderer.render(BasicTheme.java:187)
	at net.halalaboos.huzuni.gui.BasicTheme$NodeTreeRenderer.render(BasicTheme.java:175)
	at net.halalaboos.huzuni.api.gui.Theme.renderComponent(Theme.java:41)
	at net.halalaboos.huzuni.api.gui.Component.render(Component.java:29)
	at net.halalaboos.huzuni.api.gui.components.ScrollableComponent.render(ScrollableComponent.java:27)
	at net.halalaboos.huzuni.api.gui.components.tree.NodeTree.render(NodeTree.java:24)
	at net.halalaboos.huzuni.api.gui.Container.render(Container.java:31)
	at net.halalaboos.huzuni.api.gui.containers.SingleComponentContainer.render(SingleComponentContainer.java:36)
	at net.halalaboos.huzuni.gui.SettingsMenu.renderMenu(SettingsMenu.java:104)
	at net.halalaboos.huzuni.gui.screen.HuzuniSettingsMenu.func_73863_a(HuzuniSettingsMenu.java:32)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.halalaboos.huzuni.gui.screen.HuzuniSettingsMenu
	Mouse location: Scaled: (19, 172). Absolute: (59, 320)
	Screen size: Scaled: (480, 279). Absolute: (1440, 837). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 10 total; [HuzuniEntityPlayer['eLRumano'/3108, l='MpServer', x=25,31, y=44,00, z=-18,10], EntityOtherPlayerMP['momo000022'/2672556, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['Gomman23'/2651821, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['kid4info'/2599356, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['zelphire7'/2580379, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['Master_panda02'/2729410, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['darkyla'/2077675, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['MOUTONRAS'/2759832, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['Deathworld_'/2762511, l='MpServer', x=44,17, y=44,00, z=10,59], EntityOtherPlayerMP['MrSting38'/2763967, l='MpServer', x=9,41, y=50,87, z=0,51]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,50,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 61842778 game time, 1026 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 83 total; [HuzuniEntityPlayer['eLRumano'/3108, l='MpServer', x=25,31, y=44,00, z=-18,10], EntityOtherPlayerMP['momo000022'/2672556, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['Gomman23'/2651821, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['kid4info'/2599356, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['zelphire7'/2580379, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['Master_panda02'/2729410, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['darkyla'/2077675, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['Nsurr'/2755279, l='MpServer', x=67,00, y=44,09, z=0,06], EntityOtherPlayerMP['Deathworld_'/2762511, l='MpServer', x=44,17, y=44,00, z=10,59], EntityArmorStand['§f+-------------+'/38, l='MpServer', x=7,50, y=52,50, z=0,50], EntityArmorStand['§f§lBIENVENUE SUR §6§lHYPARIA'/39, l='MpServer', x=7,50, y=52,25, z=0,50], EntityOtherPlayerMP['NzoCara'/2758639, l='MpServer', x=68,41, y=44,00, z=-6,44], EntityArmorStand['§a285§7/500 connectés'/40, l='MpServer', x=7,50, y=52,00, z=0,50], EntityArmorStand['§f+-------------+'/41, l='MpServer', x=7,50, y=51,75, z=0,50], EntityArmorStand['Armor Stand'/42, l='MpServer', x=7,50, y=51,50, z=0,50], EntityArmorStand['§bPour commencer à jouer, veuillez choisir'/43, l='MpServer', x=7,50, y=51,25, z=0,50], EntityArmorStand['§bl'un de nos serveurs en cliquant sur les'/44, l='MpServer', x=7,50, y=51,00, z=0,50], EntityArmorStand['§bPNJ qui se trouvent devant vous.'/45, l='MpServer', x=7,50, y=50,75, z=0,50], EntityArmorStand['Armor Stand'/46, l='MpServer', x=7,50, y=50,50, z=0,50], EntityArmorStand['§bSi vous souhaitez revenir au lobby,'/47, l='MpServer', x=7,50, y=50,25, z=0,50], EntityArmorStand['§butilisez la commande: §6/hub'/48, l='MpServer', x=7,50, y=50,00, z=0,50], EntityOtherPlayerMP['MrSting38'/2763967, l='MpServer', x=9,41, y=50,87, z=0,51], EntityOtherPlayerMP['ccgogo'/2727620, l='MpServer', x=65,75, y=44,89, z=1,91], EntityOtherPlayerMP['megamox3000'/2752204, l='MpServer', x=48,53, y=44,00, z=0,94], EntityOtherPlayerMP['Deathworld_'/2762511, l='MpServer', x=44,17, y=44,00, z=10,59], EntityOtherPlayerMP['Azagog'/2761045, l='MpServer', x=66,92, y=45,01, z=-6,87], EntityArmorStand['§6#5 §eMasterOne84: §c141'/2762410, l='MpServer', x=49,50, y=45,00, z=23,50], EntityArmorStand['§6#6 §eDieuFoxy: §c133'/2762411, l='MpServer', x=49,50, y=44,75, z=23,50], EntityArmorStand['§6#3 §eaksel2102: §c158'/2762408, l='MpServer', x=49,50, y=45,50, z=23,50], EntityArmorStand['§6#4 §eSyes: §c147'/2762409, l='MpServer', x=49,50, y=45,25, z=23,50], EntityOtherPlayerMP['momo000022'/2672556, l='MpServer', x=0,50, y=50,00, z=0,50], EntityArmorStand['§6#9 §e_LeMeilleur_: §c121'/2762414, l='MpServer', x=49,50, y=44,00, z=23,50], EntityOtherPlayerMP['Gomman23'/2651821, l='MpServer', x=0,50, y=50,00, z=0,50], EntityArmorStand['§6#10 §eOmegaUp: §c110'/2762415, l='MpServer', x=49,50, y=43,75, z=23,50], EntityArmorStand['§6#7 §ebrendon62: §c131'/2762412, l='MpServer', x=49,50, y=44,50, z=23,50], EntityArmorStand['§6#8 §eGooDy_PiX: §c126'/2762413, l='MpServer', x=49,50, y=44,25, z=23,50], EntityArmorStand['§6#1 §eiSheawZ: §c345'/2762406, l='MpServer', x=49,50, y=46,00, z=23,50], EntityArmorStand['§6#2 §eUnScorpionPvP: §c187'/2762407, l='MpServer', x=49,50, y=45,75, z=23,50], EntityArmorStand['§f§lCLASSEMENT'/2762404, l='MpServer', x=49,50, y=46,50, z=23,50], EntityArmorStand['§bFatality (Victoires)'/2762405, l='MpServer', x=49,50, y=46,25, z=23,50], EntityArmorStand['§6#9 §ebrendon62: §c2036'/2762426, l='MpServer', x=53,50, y=44,00, z=22,50], EntityArmorStand['§6#10 §eFlappyrus: §c1996'/2762427, l='MpServer', x=53,50, y=43,75, z=22,50], EntityArmorStand['§6#7 §eaksel2102: §c2282'/2762424, l='MpServer', x=53,50, y=44,50, z=22,50], EntityArmorStand['§6#8 §eLordFiredu66: §c2258'/2762425, l='MpServer', x=53,50, y=44,25, z=22,50], EntityArmorStand['§6#1 §eAtomicGG: §c11.5'/2762430, l='MpServer', x=57,50, y=46,00, z=21,50], EntityArmorStand['§6#2 §eHezzio: §c9.27'/2762431, l='MpServer', x=57,50, y=45,75, z=21,50], EntityOtherPlayerMP['MrSting38'/2763967, l='MpServer', x=9,41, y=50,87, z=0,51], EntityArmorStand['§f§lCLASSEMENT'/2762428, l='MpServer', x=57,50, y=46,50, z=21,50], EntityArmorStand['§bFatality (Ratio)'/2762429, l='MpServer', x=57,50, y=46,25, z=21,50], EntityArmorStand['§6#1 §eiSheawZ: §c6856'/2762418, l='MpServer', x=53,50, y=46,00, z=22,50], EntityArmorStand['§6#2 §eUnScorpionPvP: §c3975'/2762419, l='MpServer', x=53,50, y=45,75, z=22,50], EntityArmorStand['§f§lCLASSEMENT'/2762416, l='MpServer', x=53,50, y=46,50, z=22,50], EntityOtherPlayerMP['kid4info'/2599356, l='MpServer', x=0,50, y=50,00, z=0,50], EntityArmorStand['§bFatality (Kills)'/2762417, l='MpServer', x=53,50, y=46,25, z=22,50], EntityArmorStand['§6#5 §eOmegaUp: §c2580'/2762422, l='MpServer', x=53,50, y=45,00, z=22,50], EntityArmorStand['§6#6 §eSyes: §c2499'/2762423, l='MpServer', x=53,50, y=44,75, z=22,50], EntityArmorStand['§6#3 §eMasterOne84: §c3780'/2762420, l='MpServer', x=53,50, y=45,50, z=22,50], EntityArmorStand['§6#4 §eVerre2Biere: §c2776'/2762421, l='MpServer', x=53,50, y=45,25, z=22,50], EntityOtherPlayerMP['MOUTONRAS'/2759832, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['zelphire7'/2580379, l='MpServer', x=0,50, y=50,00, z=0,50], EntityOtherPlayerMP['MOUTONRAS'/2759832, l='MpServer', x=0,50, y=50,00, z=0,50], EntityArmorStand['§6#1 §e10110l1000: §c35'/2762442, l='MpServer', x=61,50, y=46,00, z=19,50], EntityArmorStand['§6#2 §eMorfasio: §c16'/2762443, l='MpServer', x=61,50, y=45,75, z=19,50], EntityArmorStand['§f§lCLASSEMENT'/2762440, l='MpServer', x=61,50, y=46,50, z=19,50], EntityArmorStand['§dFatality (EVENT) (Ratio)'/2762441, l='MpServer', x=61,50, y=46,25, z=19,50], EntityArmorStand['§6#5 §eval_347: §c12'/2762446, l='MpServer', x=61,50, y=45,00, z=19,50], EntityArmorStand['§6#6 §eLord_Sans: §c7.33'/2762447, l='MpServer', x=61,50, y=44,75, z=19,50], EntityArmorStand['§6#3 §eLucky63: §c14'/2762444, l='MpServer', x=61,50, y=45,50, z=19,50], EntityArmorStand['§6#4 §eMehdi_Best: §c12'/2762445, l='MpServer', x=61,50, y=45,25, z=19,50], EntityArmorStand['§6#5 §eErwan64: §c6.07'/2762434, l='MpServer', x=57,50, y=45,00, z=21,50], EntityArmorStand['§6#6 §ecalculatorde882: §c5.81'/2762435, l='MpServer', x=57,50, y=44,75, z=21,50], EntityArmorStand['§6#3 §eOrbitTurtle: §c8.07'/2762432, l='MpServer', x=57,50, y=45,50, z=21,50], EntityOtherPlayerMP['Master_panda02'/2729410, l='MpServer', x=0,50, y=50,00, z=0,50], EntityArmorStand['§6#4 §ejujules059: §c6.67'/2762433, l='MpServer', x=57,50, y=45,25, z=21,50], EntityArmorStand['§6#9 §eAlasen: §c4.75'/2762438, l='MpServer', x=57,50, y=44,00, z=21,50], EntityArmorStand['§6#10 §exBenji02: §c4.48'/2762439, l='MpServer', x=57,50, y=43,75, z=21,50], EntityArmorStand['§6#7 §eI_Gollum: §c4.95'/2762436, l='MpServer', x=57,50, y=44,50, z=21,50], EntityArmorStand['§6#8 §eKosenn: §c4.91'/2762437, l='MpServer', x=57,50, y=44,25, z=21,50], EntityOtherPlayerMP['darkyla'/2077675, l='MpServer', x=0,50, y=50,00, z=0,50], EntityArmorStand['§6#9 §exBenji02: §c6'/2762450, l='MpServer', x=61,50, y=44,00, z=19,50], EntityArmorStand['§6#10 §eX________X: §c6'/2762451, l='MpServer', x=61,50, y=43,75, z=19,50], EntityArmorStand['§6#7 §eiSheawZ: §c7.3'/2762448, l='MpServer', x=61,50, y=44,50, z=19,50], EntityArmorStand['§6#8 §efamas9874: §c6'/2762449, l='MpServer', x=61,50, y=44,25, z=19,50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.11-SNAPSHOT:01f4448:1226) <- TacoSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 204092104 bytes (194 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce 820M/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce 820M/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz

**Comment by brudin** [comment]
This should be fixed for the next release
